language: python
sudo: false
os:
  - linux
python:
  - '2.7'
install:
  - pip install -e .
  - pip install coveralls
  - pip install coverage
  - cp tests/testrail.conf ~/.testrail.conf
script: nosetests --with-coverage --cover-package=testrail --cover-erase -v ./tests
after_success:
  - coveralls
