language: python
sudo: false
os:
  - linux
python:
  - '2.7'
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - cp tests/testrail.conf ~/.testrail.conf
script: nosetests --with-coverage -v ./tests
after_success:
  - coveralls
